# Generated by Django 5.1.7 on 2025-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_guarantordetails_loan_loandetails_guarantor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
