# Generated by Django 5.1.7 on 2025-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_repayments_repayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guarantordetails',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile/documents/guarantor/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
